name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['13.3.0', '13.4.1', '14.0.1', '14.2.0']
    steps:
      - uses: actions/checkout@v3
      - run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - run: swift build

